/*   ouput:---
 *  Number generated: 5
	Number generated: 2
	Number generated: 8
	Number generated: 9
	Number generated: 4
	sum of all the random numbers generated by threads are:28
	Main has been executed

 */
package question2;

import java.util.Random;

class MyRunnable implements Runnable{
	static int sum;
	public MyRunnable(int i) {
		this.sum=sum;
	}

	public void run() {
		Random random = new Random();
		int number = random.nextInt(10) + 1;
		synchronized (this) {
			System.out.println("Number generated: " + number);
			this.sum+= number; 
		}
		
	}
}
public class RandomNumberSumByThreads {
	
	public static void main(String[] args) {
		
		MyRunnable r =  new MyRunnable(0);
		   Thread t1 = new Thread(r);
		   Thread t2=  new Thread(r);
		   Thread t3  = new Thread(r);
		   Thread t4  = new Thread(r);
		   Thread t5  = new Thread(r);
		   t1.start();
		   t2.start();
		   t3.start();
		   t4.start();
		   t5.start();
		   
		   try {
				t1.join();
				t2.join();
				t3.join();
				t4.join();
				t5.join();
				
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			System.out.println("sum of all the random numbers generated by threads are:"+ MyRunnable.sum);
			System.out.println("Main has been executed");
	}

}
